"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
export type WorkspaceSettingsState = { error?: string; success?: string };
async function rpc(name: string, args: Record<string, unknown>) { const supabase = await createClient(); return supabase.rpc(name, args); }
export async function updateWorkspaceSettings(_state: WorkspaceSettingsState, formData: FormData): Promise<WorkspaceSettingsState> { const parsed = z.object({ name: z.string().trim().min(2), logoUrl: z.string().trim().url().or(z.literal("")) }).safeParse({ name: formData.get("name"), logoUrl: formData.get("logoUrl") }); if (!parsed.success) return { error: "Revise o nome e a URL do logo." }; const { error } = await rpc("update_workspace_settings", { workspace_name: parsed.data.name, workspace_logo_url: parsed.data.logoUrl }); if (error) return { error: error.message }; revalidatePath("/", "layout"); return { success: "Workspace atualizado." }; }
export async function addMember(_state: WorkspaceSettingsState, formData: FormData): Promise<WorkspaceSettingsState> { const parsed = z.object({ email: z.string().email(), role: z.enum(["member", "admin"]) }).safeParse({ email: formData.get("email"), role: formData.get("role") }); if (!parsed.success) return { error: "Informe um e-mail válido." }; const { error } = await rpc("add_workspace_member", { member_email: parsed.data.email, member_role: parsed.data.role }); if (error) return { error: error.message }; revalidatePath("/configuracoes/workspace"); return { success: "Membro adicionado." }; }
export async function removeMember(formData: FormData) { const parsed = z.string().uuid().safeParse(formData.get("userId")); if (!parsed.success) return; const { error } = await rpc("remove_workspace_member", { target_user_id: parsed.data }); if (!error) revalidatePath("/configuracoes/workspace"); }
export async function transferOwnership(formData: FormData) { const parsed = z.string().uuid().safeParse(formData.get("userId")); if (!parsed.success) return; const { error } = await rpc("transfer_workspace_ownership", { target_user_id: parsed.data }); if (!error) revalidatePath("/configuracoes/workspace"); }
