"use client";
import { useActionState } from "react";
import { Crown, LoaderCircle, UserPlus } from "lucide-react";
import { addMember, removeMember, transferOwnership, type WorkspaceSettingsState } from "./actions";
const initialState: WorkspaceSettingsState = {};
export function MembersManager({ members, currentUserId, currentRole }: Readonly<{ members: { userId: string; name: string; role: string }[]; currentUserId: string; currentRole: string }>) {
 const [state, formAction, isPending] = useActionState(addMember, initialState); const canManage = currentRole === "owner" || currentRole === "admin";
 return <section className="mt-12 max-w-3xl rounded-3xl border border-border bg-surface p-6 shadow-sm sm:p-8"><div><h2 className="text-lg font-medium">Convidados e membros</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Adicione pessoas que já tenham uma conta no Kanaflix CRM.</p></div>{canManage && <form action={formAction} className="mt-6 grid gap-3 sm:grid-cols-[1fr_140px_auto]"><input name="email" type="email" required placeholder="email@empresa.com" className="h-11 rounded-2xl border border-border bg-surface px-4 text-sm" /><select name="role" defaultValue="member" className="h-11 rounded-2xl border border-border bg-surface px-3 text-sm"><option value="member">Membro</option><option value="admin">Administrador</option></select><button disabled={isPending} className="inline-flex h-11 items-center justify-center gap-2 rounded-2xl bg-brand px-4 text-sm font-medium text-brand-foreground disabled:opacity-60">{isPending ? <LoaderCircle className="animate-spin" size={17} /> : <UserPlus size={17} />}Adicionar</button></form>}{state.error && <p className="mt-4 text-sm text-brand">{state.error}</p>}{state.success && <p className="mt-4 text-sm text-success">{state.success}</p>}<div className="mt-6 divide-y divide-border">{members.map((member) => <div key={member.userId} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="text-sm font-medium">{member.name}</p><p className="mt-1 text-xs text-muted-foreground">{member.role === "owner" ? "Proprietário" : member.role === "admin" ? "Administrador" : "Membro"}</p></div>{currentRole === "owner" && member.userId !== currentUserId && <div className="flex gap-2"><form action={transferOwnership}><input type="hidden" name="userId" value={member.userId} /><button className="h-9 rounded-xl border border-border px-3 text-xs hover:bg-surface-muted">Transferir</button></form><form action={removeMember}><input type="hidden" name="userId" value={member.userId} /><button className="h-9 rounded-xl px-3 text-xs text-brand hover:bg-brand-soft">Remover</button></form></div>}</div>)}</div>{currentRole === "owner" && <p className="mt-5 flex gap-2 text-xs leading-5 text-muted-foreground"><Crown size={15} className="shrink-0 text-brand" />Ao transferir, você passa a ser administrador e o novo membro vira proprietário.</p>}</section>;
}
